# Generated by Django 2.0.5 on 2018-06-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='rated',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=1900),
        ),
    ]
